CXX=g++
CXXFLAGS=-std=gnu++11 -Wall -Wextra -Wpedantic -MMD -MP
TARGET=lifeGame
RELEASE=debug
LIB_DIR=-L/usr/local/lib

LIBS=$(LIB_DIR) -lallegro \
	 -lallegro_image \
	 -lallegro_font \
	 -lallegro_ttf \
	 -lallegro_dialog \
	 -lallegro_primitives \
	 -lallegro_audio \
	 -lallegro_acodec

SRC=$(shell find . -type f -name "*.cpp")
OBJ=$(SRC:.cpp=.o)
DEPS_FLAGS=-MMD -MP
DEPS=$(SRC=.cpp=.d)

ifeq ($(RELEASE), debug)
    CXXFLAGS+=-O0 -g -gdwarf-5
else
	CXXFLAGS+=-O3 -DNDEBUG -flto -s  
endif


all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) $(LIBS) $^ -o $(TARGET) 

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

-include $(DEPS)

.PHONY: clean rebuild


clean:
	@rm -rf *.o $(TARGET) *.d

rebuild: clean
	$(MAKE) -j$(shell nproc --ignore=1)



